name: Flutter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: beta
          version: 3.24.0-0.2.pre

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web
      
      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email edawarekaro@gmail.com
          git config --global user.name richkazz
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/richkazz/input-field-error-host.git
          git checkout -b main
          git add --all
          git commit -m "update"
          git push origin main -f
